### ISSUE TITLE
Remove maritime=yes boundaries

### ISSUE THREAD

**Issue by yohanboniface** [tilery/mae-boundaries#9]
That's a request from the MEAE.

That's not that simple, sadly.
Here is the current process:
- for each country, retrieve the OSM relation
- build the polygon from it
- add or substract some areas (according to French diplomacy)

So **what we have at rendering time are polygons**, and thus the members tags are lost, we only keep the relation tags (as a whole).
And we are happy with polygons, so we can display boundary labels offset on the right side for the border line (instead of having lines in whatever direction).

I see a bunch of options:

- once computed the polygon, move back to a linestring, and substract the "maritime=yes" members of the relation (but then I'm not sure I can [force the right-hand](http://postgis.net/docs/ST_ForceRHR.html) rule so we can control which side to offset the labels)
- once computed the polygon, make an intersection with the land polygons
- CartoCSS side, redraw the `maritime=yes` line above with water color, to hide the borders
- CartoCSS side, instead of drawing land over a water background, draw water above a land background, so we can also draw the admin lines below the water

cc @cquest any better idea?

**Comment by yohanboniface** [comment]
If I try to use [split polygons](http://openstreetmapdata.com/data/land-polygons), I go into troubles:

```
asyncpg.exceptions.InternalServerError: Error performing intersection: TopologyException: Input geom 0 is invalid: Nested shells at or near point 56.2724932 25.279528200000001 at 56.2724932 25.279528200000001
```

Which point to those nested boundaries: https://www.openstreetmap.org/relation/307763#map=13/25.2758/56.2780

Request was:
```sql
SELECT ST_Intersection(ST_SetSRID($1::geometry, 4326),
                                        (SELECT ST_Collect(geom)
                                         FROM land
                                         WHERE ST_Intersects(ST_SetSRID($1::geometry, 4326), geom)))
```

**Comment by yohanboniface** [comment]
Using complete polygons, the processing (same SQL as above) works (but takes ages, 2h30, [details](https://paste.sh/wgELPKor#437Rd7zQ6ITVYoT5Fp5dCkVa)), but then the import (with ogr2ogr) complains:

```
ERROR 1: GeoJSON object too complex
ERROR 1: GeoJSON object too complex
ERROR 1: GeoJSON object too complex
ERROR 1: GeoJSON object too complex
ERROR 1: GeoJSON object too complex
…
```

Of course, we have all coastline details, eg. for United Arab Emirates: https://gist.github.com/yohanboniface/282cdc53692241f588317c9f649dfe9e

**Comment by yohanboniface** [comment]
With an `ST_Boundary`, we have something (but it still takes 2 hours and half to process):

```sql
SELECT ST_Intersection(ST_SetSRID(ST_Boundary($1::geometry), 4326),
    (SELECT ST_Collect(geom)
    FROM land
    WHERE ST_Intersects(ST_SetSRID($1::geometry, 4326), geom)))
```
![screenshot from 2018-10-01 20-31-58](https://user-images.githubusercontent.com/146023/46311510-bffa9d80-c5c2-11e8-9c73-eed6da3d1a38.png)

**Comment by yohanboniface** [comment]
Grml, even with `ST_ForceRHR`, we cannot control the offset direction, it seems the lines directions are random:

![screenshot-20181002134402-1752x1452](https://user-images.githubusercontent.com/146023/46346728-5671a200-c649-11e8-82b1-624c9b1dae95.png)

```
SELECT ST_Intersection(ST_SetSRID(ST_Boundary(ST_ForceRHR($1::geometry)), 4326),
    (SELECT ST_Collect(geom)
    FROM land
    WHERE ST_Intersects(ST_SetSRID($1::geometry, 4326), geom)))
```

**Comment by yohanboniface** [comment]
We good it seems!

![screenshot-20181002225314-1506x1262](https://user-images.githubusercontent.com/146023/46376304-f6edb380-c695-11e8-8060-037808df9b1c.png)

```sql
SELECT ST_Intersection(ST_SetSRID(ST_Boundary(ST_ForcePolygonCCW($1::geometry)), 4326), 
    (SELECT ST_Collect(geom)
    FROM land
    WHERE ST_Intersects(ST_SetSRID($1::geometry, 4326), geom)))
```

**Comment by kent1D** [comment]
Bravo ;)
